# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9fc87be81c6093c06726b5b6b508b68e"
application_url = "https://asset-dust-icons-responding.trycloudflare.com"
embedded = true
name = "marh18"
handle = "marh18"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://asset-dust-icons-responding.trycloudflare.com/auth/callback",
  "https://asset-dust-icons-responding.trycloudflare.com/auth/shopify/callback",
  "https://asset-dust-icons-responding.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
